adobe-photoshop/generator-assets

npm-shrinkwrap.json
package.json

Points at the recently branched "release-0.3" branch that has several bugfixes.  QE has made a pass at verifying the fixes.  This PR will bring in the latest and greatest SVG output.

update OMG pointer to latest SVG

---

package.json

We're doing the same thing in Crema.

Update fs-extra to latest version. Allow npm i --save to alphabetize deps in package.json.

---

lib/dom/document.js
lib/renderer.js

Also, fixes a bug in document content bounds computation to make clipping work correctly for layer comps and full document export.
@jaredadobe Review please?

Support full document export as a bitmap format or SVG.

---

lib/renderer.js

Get interpolationType from component
cc @chrisbank

Get interpolationType from component

---

etc/layernames.pegjs
lib/componentmanager.js
lib/dom/bounds.js
lib/parser.js
lib/renderer.js
test/test-parse-layer-name.js

This is the initial implementation for canvas size cropping or padding. We will need some other tweaks but QE is satisfied this doesn't break any current functionality and is ready to go it.

crop or pad images using canvas size

---

lib/assetmanager.js
lib/componentmanager.js
lib/errormanager.js
lib/renderer.js
lib/rendermanager.js

@wyles @chrisbank This is the generator-assets side of full document export. (I will squash into one commit before merging.)

Doc export as

---

lib/renderer.js

This exposes the generator.streamPixmap API to the users of the render.

expose streaming api

---

lib/renderer.js

This uses the settings added in this pull https://github.com/adobe-photoshop/generator-core/pull/315

add support for useICCProfile setting

---

lib/renderer.js
npm-shrinkwrap.json
package.json

Update to svgomg 0.6
cc @chrisbank

svgomg 0.6

---

npm-shrinkwrap.json

Update shrinkwrap for svgOMG fixes

Update shrinkwrap for svgOMG fixes

---

npm-shrinkwrap.json

another update to svgomg release-0.6

Another update to svgomg release-0.6

---

npm-shrinkwrap.json

More updates for release-0.6

---

npm-shrinkwrap.json
package.json

I also updated package.json version to 2.5.0-dev to match what we have in nom-shrinkwrap.json (and have been updating manually).

Update shrinkwrap for svgomg change

---

lib/dom/layer.js
lib/renderer.js

enlarge content bounds when a fill layer in an artboard is found

expand bounds to artboard bounds when a fill layer is found

---

lib/renderer.js

expand to document bounds for fill layers

also expand document bounds for fill layers

---

lib/renderer.js

fix for https://jira.corp.adobe.com/browse/PS-2286

Force hidden layers to use exact bounds

---

lib/renderer.js

use exact bounds if we have a layer with non integral bounds

---

lib/renderer.js

requires g-a-a PR https://github.com/adobe-photoshop/generator-assets-automation/pull/41

set useFlite to true by default

---

lib/renderer.js
package.json

requires generator-core pr #378

revert target size work

---

lib/rendermanager.js

Merge commit from #433 into master

Emit Component with "render" event

---

package-lock.json
package.json

see: https://github.com/adobe-photoshop/svgObjectModelGenerator/pull/4

Use svgobjectmodelgenerator 0.6.4 which now includes background layers in SVG

---

lib/dom/document.js
test/resources/all-layer-types-docinfo-from-dom.json

This should have no effect on the current version of photoshop.

Adding experimental properties to dom/document, for testing
