- lib/assetmanager.js
- lib/componentmanager.js
- lib/parsermanager.js
- main.js
Controlled by a config option ‘meta-data-driven’
For development/testing add the generator.json config option "meta-data-test-menu-enabled" that enables 2 menus in File > Generate
1) "Apply meta-data to selection" adds hard-coded meta data to the selected layer and creates a global meta-data spec (2x and 0.5x)
2) "Layer syntax to meta-data" parses the selected layers and stores the result in meta-data.
> meta-data driven

- lib/componentmanager.js
The PSDs I try sometimes bring down generator assets because `layer._generatorSettings` is undefined.
@chrisbank Review please?
> Don't crash generator assets when there is no layer metadata.

- lib/asyncqueue.js
- lib/filemanager.js
- Added targetPath as the resolved result of fileManager's `moveFileWithin` and `moveFileInto` methods
- Noted that `moveFileWithin` might be dead code
- Added a new `moveFileAbsolute` to support the Design Space export process
- Updated `asyncqueue` so that as jobs complete, the underlying deferred is resolved with *the return value*
- Updated `asyncqueue` so that as jobs error, the underlying deferred is rejected with that error
> Added an absolute version of the move file method of FileManager

- npm-shrinkwrap.json
- package.json
Note that svgObjectModelGenerator `release-0.5` branch has not yet been merged to `master` because automated testing is not yet ready.
cc @chrisbank
> Update to svgomg release-0.5 branch

- lib/renderer.js
This adds the option to use the flitetranscoder support added to generator core. By default generate-assets does not use it. This can get override at a global level using a configuration json file with ```use-flite: true```and at the individual component level by plugins rendering components.
> changes to optional use flite for image encoding

- lib/documentmanager.js
This adds two options to speed up captive uses if the Document Manager. 
The first is the ability to specify what flags to pass to getDocumentInfo. In particular the `getTextStyles: false` will greatly speed up the getDocumentInfo call if you don't need to use text styles. 
The other is an option to clear the document managers document cache on change instead of trying to keep the cache up to date. This means the next call of getDocument() is called after an edit will call getDocumentInfo, but it keeps PS from doing a lot of extra work on each edit.
> options for faster DocumentManager instances

- lib/renderer.js
when calculating the max size to export an image, need to include the scale
Here is the bug number : https://watsonexp.corp.adobe.com/#bug=4065468
> include scale when calculating maxBounds

- lib/renderer.js
Updating zero bound check to include document level check also. In some cases docInfo is not updated and it ends up getting zero bounds at the doucment level also. In such a case it's better to get bounds using  `_getSettingsWithExactBounds`
This was squashed and split off of PR #369, so see conversation there.
> Updating zero bound check to include document level check

- lib/renderer.js
also preserve float values as long as possible
#3975340 Export whole document/scaled: testfile is exported incorrectly (some layers are not clipped to doc bound; areas outside of doc canvas are in the asset and only half of actual image is in asset)
> don't scale the limit for the starting dimensions

- lib/renderer.js
commit d3843d7780093abec893ed51a0f6fa3340b5944f
Merge: 0a40204 90a3584
Author: Vic Mitnick <vmitnick@adobe.com>
Date:   Wed Oct 21 15:28:23 2015 -0700
Merge branch 'master' into vmitnick/layer-effect-optimiz
commit 0a402045a78feddaf70d428f9ede72be13290233
Author: Vic Mitnick <vmitnick@adobe.com>
Date:   Wed Oct 21 10:32:24 2015 -0700
Fix a half-typo that was left over after merging with master.
commit 3578c4879e756b219f3ac66565b348b80271a3ea
Merge: a39e635 ced18ed
Author: Vic Mitnick <vmitnick@adobe.com>
Date:   Tue Oct 20 16:49:26 2015 -0700
Merge branch 'master' into vmitnick/layer-effect-optimiz
commit a39e6357f88adbe433ae3b1a25a2ac931bb84431
Author: Vic Mitnick <vmitnick@adobe.com>
Date:   Tue Oct 20 15:36:58 2015 -0700
Remove a couple debugging log statements.
commit …
> Squashed commit of the following:

- lib/renderer.js
Adding check for complex Masks on Layer group. In such presence we should resort to `_getSettingsWithExactBounds()`.
It fixes the bug : Quick Export Not Respecting Document Boundaries (file with layer mask) - 4019840
Creating new for https://github.com/adobe-photoshop/generator-assets/pull/376 since the merge was complex and there was risk of loosing some changes.
> Adding check for complex Masks on Layer group

- lib/dom/layereffects.js
- lib/renderer.js
aab0fe466cac110e410c1e638368ab5dc86d2800 is for bug 4081902 (multifx layer's not working)
b317668b4dd0b606aaa0190a9f880223a7d4c46a is for bug 4080775 (layer fx on a object within document bounds when exporting that document)
a20bf31847f881c8e07f4d3d6db88d1904a21d68 is for bug 3997873 and 4081414 (both smart object with smart filters applied)
> check for multifx props too

- lib/renderer.js
- package.json
use new api to embed icc color profile in images generated by flitetranscoder
This is the companion pull to https://github.com/adobe-photoshop/generator-core/pull/326
> use new api to embed icc color profile in images

- lib/rendermanager.js
This addresses #389.
When handling an `imageChanged` event from photoshop, if a `bounds` property exists on the event then it is assumed that we'll need to re-fetch the entire document; see [here](https://github.com/adobe-photoshop/generator-assets/blob/6894b41c914ce2b196d36ef8f6c793525e9a755d/lib/dom/document.js#L772-L777).
The problem was that the `Document` to which the `renderer` had a reference was never updated.  The reset-document process nukes that document from the DocumentManager and re-fetches it.  But at render-time, the old stale renderer was retrieved from renderManager; [see here](https://github.com/adobe-photoshop/generator-assets/blob/6894b41c914ce2b196d36ef8f6c793525e9a755d/lib/rendermanager.js#L131) 
Separately, the "end" handler in `main.js`, which stops/re-starts the …
> Delete a document's renderers when stopping or initializing an AssetManager

- lib/renderer.js
This addresses #387 and, more importantly, a general regression that prevented layer comps from being scaled by providing height/width values.  I believe this was introduced by PR #374 which limited the `hasComplexTransform` calculation to components with layers.  This current PR relaxes that slightly to allow the calculation for layers *or* layer comps.  This ultimately allows `_getSettingsWithExactBounds` to be used, which handles the explicit width/height-based scaling.
> Allow layer comps to be handled with complex transform

- lib/renderer.js
- package.json
Turns flite and jpeg optimal encoding on by default as well 
requires https://github.com/adobe-photoshop/generator-core/pull/334
>  add support for jpeg optimal huffman encoding

- lib/renderer.js
Asset side cleanups for transition away from always using bounds to define scale factor. see Core CL https://github.com/adobe-photoshop/generator-core/pull/336
> dont assume inputRect and OutputRect always exist

- lib/renderer.js
fix for issue https://github.com/adobe-photoshop/generator-assets/issues/399
> Vector masks should also force a exact bounds call

- lib/dom/document.js
What it says.  This is to clean up the logs a bit.  I noted a TODO item that these properties could actually be useful in the future.
> Suppress 'unhandled property' messages for some known new event props

- lib/renderer.js
since Photoshop now does our scaling we shouldn't need to carea bout non integer scales.
There is a layer comp test in G-a-a that fails if you remove the test for layer comps, so for now i only did layers.
> expand the use of approximate bounds for layers

- lib/renderer.js
at this point we only want to need to  use exact bounds for layer comps with resizing causes.
> swtich to PS handling target size

- lib/rendermanager.js
I need to get the details of each generated file specially its name... currently the only way possible to do this is by reading the filesystem after everything has been generated... something along these lines:
```
const generatedAssets = glob.sync(__dirname + '/*-assets/*.*');
```
By emitting  this ```component``` object on ```render``` would be of a great value :)
> Actually i meant to push it to the 2.7.4(5?) as its on npm
> Pass component onRender

- Gruntfile.js
- lib/assetmanager.js
- lib/documentmanager.js
- lib/dom/document.js
- lib/statemanager.js
- main.js
- npm-shrinkwrap.json
- package.json
This is a significant change to the feature set of this plugin.  To reduce both code complexity and photoshop performance impact, this PR removes the `imageChanged` event listener.  This means that the plugin will no longer keep track of the current document state and will no longer attempt to re-generate assets as the document changes.  The user must explicitly re-invoke the plugin via menu command.
This also has an impact on other plugins that use this repo as a module dependency IFF they rely on the AssetManager's re-rending feature.  Otherwise, the DocumentManager and AssetManager can continue to be used to perform renderings based on the state of the document when instantiated.
> On demand asset generation, do not listen to imageChanged

- lib/dom/layer.js
- lib/renderer.js
- npm-shrinkwrap.json
- package.json
Layer groups may be one of three types, all of which should be treated the same within generator.  Includes an upgrade SVG OMG dependency which contains similar changes.
> Support different flavors of layer groups

- lib/documentmanager.js
Export As uses generator-assets (as a lib) in "clearCacheOnChange" mode, which just nukes the cached document info each time an `imageChanged` event is received.  This is different from the default behavior of generator-assets (the plugin) which tries to do smarter things with each imageChanged events; keeping the document information in sync.
This PR makes a fairly narrow change to NOT clear the cached document if the change was "metaDataOnly".  This attempts to fix an issue where saving a document (which may take a long time, in the background) can interfere with a "quick export" initiated immediately following a "save".
> Change behavior of clearCacheOnChange (used by export as) to ignore metaDataOnly changes

- lib/documentmanager.js
This is a follow up to #443 which introduced a new bug that prevents generatorSettings updates from clearing the cached document.  This only affects crema (Export As) which operates in `clearCacheOnChange` mode.
This PR just narrows down the set of imageChanged events which are treated as safe to: metaDataOnly except when generatorSettings are included
This seems fairly rational, I think, that generatorSettings are special cases.
> Allow imageChanged events with generatorSettings to clear the document from cache

- lib/documentmanager.js
This is similar to the recent PR #444 
Layer selection changes are another class of "metaDataOnly" imageChanged events that needs to flush the document cache (in the case of Export As).
> flush cache  on metadataonly if selection included

- lib/renderer.js
- package-lock.json
- package.json
Provide the "useFlite" config property to svgOMG.  The new default in svgOMG will be to use flite, BUT this allows us to turn it off if necessary via the existing generator-assets `use-flite` config property.
TODO:
~[x] update package.json to point to new version of svgomg after this PR is merged: https://github.com/adobe-photoshop/svgObjectModelGenerator/pull/3~
> Provide useFlite parameter to svgomg

- main.js
`_setConfig()` is used by `generator-assets-automation`.  This new argument allows the configs to be merged in to the existing set instead first deleting all properties.
> Support g-a-a option to honor standard g-a configs during tests

- Gruntfile.js
- lib/assetmanager.js
- lib/documentmanager.js
- lib/dom/document.js
- lib/statemanager.js
- main.js
- npm-shrinkwrap.json
- package.json
Reverts adobe-photoshop/generator-assets#437
The development of this "on demand" change to generator-assets' behavior has been set aside for now.  This PR reverts back to version 2.9 so that we can bring the `master` branch up to date with the active development that has been done over the last year in the `2.9` branch.
The on-demand feature work has been moved to a separate branch
https://github.com/adobe-photoshop/generator-assets/commits/feature/on-demand
> Revert "On demand asset generation, do not listen to imageChanged"

- lib/dom/document.js
- lib/renderer.js
- package-lock.json
- package.json
-Add `mode` to the DOM.  Export As needs this to determine SVG compatibility (non-RGB documents)
-Use SVGOMG 0.6.5 which handles more gracefully the situation when the document can not be "normalized" for SVG extraction
-Return a special error property when SVG renderer throws
> SVG error handling improvements

- lib/statemanager.js
Added a catch to the `generator.getDocumentSettingsForPlugin` promise which will reject if the document has been closed.  This happens (at least) when a document is opened and then quickly closed.
> Handle rejection of getDocumentSettingsForPlugin in statemanager to avoid 'quick close' race case

- main.js
Unhandled rejections in `Q`'s `.done()` method are thrown up and out, and that crashes generator.  We have a number of situations where `getDocumentInfo` fails due to a photoshop error.  This PR handles these situations more gracefully.  The document is ignored, and errors are written to generator's logs.
> If getDocumentInfo fails, write error but don't crash generator
